### ISSUE TITLE
mem.

### ISSUE THREAD

**Issue by sniper-noob** [origolab/origo-binary#4]
Hi.
Node run for like 4 min then mem usage spike and hole server die. I use 8G mem.

**Comment by sniper-noob** [comment]
Hi.
One more thing. the Node dosent push pow to miner.

![Skjermbilde](https://user-images.githubusercontent.com/22121200/67790029-4d821880-fa75-11e9-857b-9356ceacf40a.PNG)

**Comment by cowboyorigo** [comment]
Hi, would you mind offering more details about your running environment?

- what is your running OS?
- what's the command you launch the node?
- Do you have a `config.toml` file? If so, please paste it here.

We will try to reproduce your issue based on these details. 

Thanks

**Comment by sniper-noob** [comment]
Hi.
1.
 Ubuntu 18.04

2
../origo --chain=medietas-testnet --config=config.toml

3.

[mining]
author = "0xfce39203b000e1c142ce4168b52e1d7261a0d6dc"
force_sealing = true
reseal_on_txs = "all"
reseal_min_period = 4000
reseal_max_period = 60000
tx_queue_size = 8192

[stratum]
disable = false

---
I have also tried -- stratum --stratum port -expose  etc.

so the problem node crash and node dont send pow to 
external miner, as you see in the picture the miner connect to the node but dont get pow.

thank you.

**Comment by ericripi** [comment]
the miner should get work from the node by sending "mining.subscribe",  the message format is :
    Request ：   {"params": [], "id":"x", "method": "mining.subscribe"}
    Response： {"result": ["task_id", "pow_hash", "target", "block_number"], "id":"x"}

if the miner find the equihash solution, the miner can send "mining.submit", the message format is :
    submit:       {"params":  ["task_id", "block_number", "pow_hash", "nonce", "solution"], "id": "y", "method": "mining.submit"}
    Response:  {"result":true,"id":y}   (solution have been accepted)

Which miner do you use?   if it is your own miner,   please check if your miner had send  "mining.subscribe" to the node.

**Comment by sniper-noob** [comment]
Hi. 
I use gminer  Algo192_7. It have build in Stratum v1. As I understand it,  use stratum V1 (https://github.com/nicehash/Specifications/blob/master/EthereumStratum_NiceHash_v1.0.0.txt).
it should work but miner connect and never get pow.

**Comment by ericripi** [comment]
If you use stratum v1,  you must use the RPC call of "eth_getWork"  to get work from the node, our default RPC port is 6622.
response of "eth_getWork" is  `{"jsonrpc":"2.0","result": ["pow_hash", "target", "block_number"], "id":"x"} `
this is an example:   
`curl --data '{"jsonrpc":"2.0","method":"eth_getWork","params":[],"id":1}'  -H "Content-Type: application/json" -X POST http://127.0.0.1:6622
{"jsonrpc":"2.0","result":["0x9b559a872a990c285c50fd715b4c170cc8877e8cad6e800159b9a82e79271b076f00f21800fd0a977afecad608025fe6ea49b8ae5a60c5c52d117ca8e0d0aba6","0x13b13b13b13b13b13b13b13b13b13b13b13b13b13b13b13b13b13b13b13b13b1","0x2250e"],"id":1}`

I guess that the node doesn't crash,   only gminer can't get any response from the node.

there is one miner you can try,   you can download  ogominer from https://github.com/origolab/origo-binary/tree/master/tools/miner/gpuminer

we are glad that you build your own miner， we can share  more information about mining with origo，thanks

**Comment by sniper-noob** [comment]
Hi.
TBH I run the node over night and its was crashed the hole vps and rebooted.  Going to run it over night to day and see:)

**Comment by ericripi** [comment]
Do your miner and the origo node on the same VPS?   maybe  you can  check the sys log to find out which process  had made the system crashed

**Comment by sniper-noob** [comment]
running on windows now and works fin:) now to figur out if there is a miner out there can mine the algo used by Origo.
